name: Teste simples
run-name: Iniciando

on:
  push:

permissions:
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - name: Instalar Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

  test:
    name: Teste
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: ğŸ” Verificar Node
        run: |
          node --version
          npm --version

  executar:
    name: Executar
    runs-on: ubuntu-latest
    needs: teste
    steps:
      - name: Executar script
        run: node higher_order_function.js

