name: Teste simples
run-name: Pipeline automático

on:
  push:
    paths-ignore:
      - README.md

permissions:
  contents: write

jobs:
  setup:
    name: Setup 
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - name: Instalar Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

  teste:
    name:  Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Instalar Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Testar instalação
        run: |
          node --version
          npm --version

  executar:
    name: Executar 
    needs: teste
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - name: Executar arquivo
        run: |
          node higher_order_function.js > resultado.txt

