name: Teste simples
run-name: Iniciando

on:
  push:

permissions:
  contents: write

jobs:
  setup:
    name: ğŸ”§ Setup
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Instalar Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

  teste:
    name: ğŸ§ª Teste
    needs: setup
    steps:
      - name: ğŸ” Verificar Node
        run: |
          node --version
          npm --version

  executar:
    name: â–¶ï¸ Executar
    needs: teste
    steps:
      - name: â–¶ï¸ Executar script
        run: node higher_order_function.js

